In [1]:
import pandas as pd

# Pandas
- Integer Data Type : int64
- index : 정수기반(0,1,2,...), 이름기반

In [ ]:
pd.Series((10,20,30))
# pd.Series({10,20,30})
s1 = pd.Series([10,20,30])
print("s1[0:2] :", s1[0:2])

cols = ['A', 'B', 'C']
data = [10,20,30]
s1.index = cols
print(s1)

s2 = pd.Series(data, cols)
print(s2)
print(s2['A'])
print(s2[['A','B']])
print(s2['B':'C'])

dict = {'A':40, 'B':50, 'C':60}
s3 = pd.Series(dict)
print(s3)

In [ ]:
population = pd.Series([9776, 2729, 1566, 3158], 
                    index=['서울', '부산', '인천', '대구'])
print(population['서울'])  # 9776 출력
print(population[['서울', '부산']])  # 서울과 부산의 데이터만 선택 : 리스트 형태가 아니면 행, 열 선택으로 인지 <-- 지원안함
print(population['서울' : '인천'])  # 서울 ~ 인천(포함)의 데이터만 선택
population['제주'] = 666

print(population)

In [ ]:
# 리스트로 시리즈 생성
data = [1, 2, 3, 4, 5]
s1 = pd.Series(data)
print(s1)

# 인덱스 지정하여 시리즈 생성
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
s2 = pd.Series(data, index=index)
print(s2)

# 딕셔너리로 시리즈 생성 - 키가 인덱스가 됨
dict_data = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
s3 = pd.Series(dict_data)
print(s3)

In [ ]:
# 리스트로 데이터프레임 생성
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

df = pd.DataFrame(data)
print(df)

# 열 이름 지정하여 생성
col_names=['A', 'B', 'C']
index = [10, 20, 30]
df = pd.DataFrame(data, index=index, columns = col_names)
print(df)

In [ ]:
import numpy as np
import pandas as pd

# 2차원 넘파이 어레이 생성
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# 데이터프레임 생성
df = pd.DataFrame(arr, columns=['A', 'B', 'C'])
print(df)

In [ ]:
# 시리즈 생성
names = pd.Series(['김철수', '이영희', '박민수'])
ages = pd.Series([25, 28, 22])
scores = pd.Series([85, 92, 78])

# 시리즈를 딕셔너리로 묶어 데이터프레임 생성
df = pd.DataFrame({
    '이름': names,
    '나이': ages,
    '점수': scores
})
print(df)

data = {
    '이름': ['김철수', '이영희', '박민수'],
    '나이': [25, 28, 22],
    '점수': [85, 92, 78]
}
df = pd.DataFrame(data)
print(df)

In [ ]:
# 샘플 데이터프레임 생성
data = {
    '이름': ['김철수', '이영희', '박민수', '정수진', '최영호', '한미래', '윤지원'],
    '나이': [25, 28, 22, 31, 27, 24, 29],
    '점수': [85, 92, 78, 95, 88, 73, 91]
}
df = pd.DataFrame(data)

# 처음 5개 행 보기
print("=== head() ===")
print(df.head())

# 마지막 3개 행 보기
print("\n=== tail(3) ===")
print(df.tail(3))

# 데이터프레임 기본 정보
print("\n=== info() ===")
print(df.info())

# 기술 통계량
print("\n=== describe() ===")
print(df.describe())

In [ ]:
# 데이터 입력 (성 포함 이름)
data = {
    "이름": [
        "김민수", "이영지", "박현우", "최서연", "정준호",
        "한예린", "조도윤", "신수빈", "오재민", "강하린"
    ],
    "나이": [25, 23, 30, 27, 29, 22, 31, 24, 28, 26],
    "점수": [88, 92, 75, 85, 90, 95, 70, 80, 89, 93]
}

# DataFrame 생성
df = pd.DataFrame(data)

# 처음 5개 행 보기
print("=== head() ===")
print(df.head())

# 마지막 3개 행 보기
print("\n=== tail(3) ===")
print(df.tail(3))

# 데이터프레임 기본 정보
print("\n=== info() ===")
print(df.info())

# 기술 통계량
print("\n=== describe() ===")
print(df.describe())

df.index = [
    "사과",
    "바나나",
    "포도",
    "딸기",
    "오렌지",
    "수박",
    "복숭아",
    "키위",
    "파인애플",
    "망고"
]

#  df.rename({'파인애플':'참외'}, inplace=True) # 비추
# df_2 = df.rename({'파인애플':'참외'})
df_2 = df.rename(index={'파인애플':'참외'})

df_2 = df.rename(columns={'이름':'name'})

print(df_2)

In [56]:
data = {
    "이름": [
        "김민수", "이영지", "박현우", "최서연", "정준호",
        "한예린", "조도윤", "신수빈", "오재민", "강하린"
    ],
    "나이": [25, 23, 30, 27, 29, 22, 31, 24, 28, 26],
    "점수": [88, 92, 75, 85, 90, 95, 70, 80, 89, 93]
}

# DataFrame 생성
df = pd.DataFrame(data)
df.index = ['A','B','C','D','E','F','G','H','I','J']
df.columns = ['name', 'age', 'score']

print(df)

  name  age  score
A  김민수   25     88
B  이영지   23     92
C  박현우   30     75
D  최서연   27     85
E  정준호   29     90
F  한예린   22     95
G  조도윤   31     70
H  신수빈   24     80
I  오재민   28     89
J  강하린   26     93

# loc vs iloc
- DataFrame.loc['행이름':'행이름', '열이름':'열이름']
- DataFrame.iloc['행번호':'행번호', '열번호':'열번호']]

In [4]:
# 연습문제
# [기본]

# 모든 행에서 이름 열만 선택하세요.
print(df['이름'])

# 모든 행에서 이름과 score 열을 선택하세요.
print(df[['이름', '점수']])

# 인덱스 C 행의 모든 데이터를 선택하세요.
print(df.loc['C'])

# 인덱스 D 행의 age 값만 선택하세요.
print(df.loc['D','나이'])

A    김민수
B    이영지
C    박현우
D    최서연
E    정준호
F    한예린
G    조도윤
H    신수빈
I    오재민
J    강하린
Name: 이름, dtype: object
    이름  점수
A  김민수  88
B  이영지  92
C  박현우  75
D  최서연  85
E  정준호  90
F  한예린  95
G  조도윤  70
H  신수빈  80
I  오재민  89
J  강하린  93
이름    박현우
나이     30
점수     75
Name: C, dtype: object
27

In [21]:
# [조건 + loc]

# age가 27 이상인 행만 선택하세요.
print(df.loc[df['나이']>27])

# score가 90 이상인 사람의 이름과 score만 출력하세요.
print(df.loc[df['점수']>=90, ['이름', '점수']])

# age가 25 이상이면서 score가 90 이상인 행을 모두 선택하세요.
print(df.loc[(df['점수']>=90) & (df['나이']>27)])

# iloc 인덱싱 & 슬라이싱 연습문제

    이름  나이  점수
C  박현우  30  75
E  정준호  29  90
G  조도윤  31  70
I  오재민  28  89
    이름  점수
B  이영지  92
E  정준호  90
F  한예린  95
J  강하린  93
    이름  나이  점수
E  정준호  29  90

In [28]:
# [슬라이싱]

# 인덱스 B부터 E까지의 모든 행을 선택하세요.
print(df.loc['B':'E'])

# 인덱스 C부터 F까지의 이름과 age 열만 선택하세요.
print(df.loc['B':'E', ['이름', '나이']])

# 인덱스 A부터 G까지에서 score 열만 선택하세요.
print(df.loc['A':'G', ['점수']])

    이름  나이  점수
B  이영지  23  92
C  박현우  30  75
D  최서연  27  85
E  정준호  29  90
    이름  나이
B  이영지  23
C  박현우  30
D  최서연  27
E  정준호  29
   점수
A  88
B  92
C  75
D  85
E  90
F  95
G  70

In [ ]:
# 👉 정수 위치 기반 (0부터 시작)

# [기본]

# 첫 번째 행의 모든 데이터를 선택하세요.
print(df.iloc[0])

# 세 번째 행의 이름 값만 선택하세요.
print(df.iloc[2, 0])

# 처음 3개의 행을 선택하세요.
print(df.head(3))

# 마지막 행의 score 값만 선택하세요.
print(df.iloc[-1, 2])

이름    김민수
나이     25
점수     88
Name: A, dtype: object
박현우
    이름  나이  점수
A  김민수  25  88
B  이영지  23  92
C  박현우  30  75
93

In [ ]:
# [슬라이싱]

# 1번 행부터 4번 행까지 선택하세요.
print(df.iloc[1:5])

# 2번 행부터 5번 행까지에서 이름과 age 열만 선택하세요.
print(df.iloc[2:6, 0:2])

# 모든 행에서 age 열만 선택하세요.
print(df.iloc[:, 2])

    이름  나이  점수
B  이영지  23  92
C  박현우  30  75
D  최서연  27  85
E  정준호  29  90
    이름  나이
C  박현우  30
D  최서연  27
E  정준호  29
F  한예린  22
A    88
B    92
C    75
D    85
E    90
F    95
G    70
H    80
I    89
J    93
Name: 점수, dtype: int64

In [41]:
# [조합 문제]

# score 열만 선택하되, 앞에서 4개의 행만 출력하세요.
# print(df.head(4)['점수'])
print(df['점수'].head(4))

# 이름과 score 열을 선택하되, 마지막 3개의 행만 출력하세요.
print(df[['이름','점수']].tail(3))

# 짝수 번째 행(0, 2, 4, 6)의 모든 데이터를 선택하세요.
print(df.iloc[0::2])

A    88
B    92
C    75
D    85
Name: 점수, dtype: int64
    이름  점수
H  신수빈  80
I  오재민  89
J  강하린  93
    이름  나이  점수
A  김민수  25  88
C  박현우  30  75
E  정준호  29  90
G  조도윤  31  70
I  오재민  28  89

In [57]:
# loc를 사용하여 새로운 행 추가
# df.loc['H'] = ['장민호', 26, 88]


# 여러 행 한 번에 삭제
# df = df.drop(['E', 'F', 'G'], axis=0)

# 여러 열 한 번에 삭제
df.drop(['나이', '점수'], axis=1)

# 직접 할당으로 열 추가
df['grade'] = ['A', 'B', 'A', 'A', 'B', 'C', 'A']
df

KeyError: "['나이', '점수'] not found in axis"

In [70]:
data = {
    "이름": [
        "김민수", "이영지", "박현우", "최서연", "정준호",
        "한예린", "조도윤", "신수빈", "오재민", "강하린"
    ],
    "나이": [25, 23, 30, 27, 29, 22, 31, 24, 28, 26],
    "점수": [75, 92, 75, 85, 60, 95, 70, 80, 89, 93]
}

# DataFrame 생성
df = pd.DataFrame(data)
df.index = ['A','B','C','D','E','F','G','H','I','J']
df.columns = ['name', 'age', 'score']

df.insert(loc=1, column='student_id', value=['S001', 'S002', 'S003', 'S004', 'S005', 'S006', 'S007', 'S008', 'S009', 'S010'])
df['grade'] = ['A' if score >= 90 else ('B' if score >= 80 else ('C' if score >= 70 else 'D') ) for score in df['score']]

df.set_index('student_id', inplace=True)
df

           name  age  score grade
student_id
S001        김민수   25     75     C
S002        이영지   23     92     A
S003        박현우   30     75     C
S004        최서연   27     85     B
S005        정준호   29     60     D
S006        한예린   22     95     A
S007        조도윤   31     70     C
S008        신수빈   24     80     B
S009        오재민   28     89     B
S010        강하린   26     93     A

In [73]:
data = [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]

df = pd.DataFrame(data)
print(df)

def square(x, e=2) :
    return x**e

df = df *2
df 

df = df.apply(square, e=3)
df

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

      0     1     2
0     8    64   216
1   512  1000  1728
2  2744  4096  5832

In [5]:
import pandas as pd 

data = {
    "name": ["김민수", "이서연", "박현우", "최지은", "정도윤"],
    "age": [29, 34, 41, 27, 36],
    "salary": [52000, 68000, 75000, 48000, 82000]
}

# DataFrame 생성
df = pd.DataFrame(data)

df.info()

def age_category(age) :
    age_cat = ""
    if age < 30 : 
        age_cat = "20대이하"
    elif age < 40 :
        age_cat = "30대"
    elif age < 50 :
        age_cat = "40대"
    else :
        age_cat = "50대이상"
    
    return age_cat
        

df["age category"] = df['age'].apply(age_category)
df['bonus'] = [salary*0.2 for salary in df['salary']]
df['bonus'] = df['bonus'].astype(int)
df.info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      int64
 2   salary  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes

<bound method DataFrame.info of   name  age  salary age category  bonus
0  김민수   29   52000        20대이하  10400
1  이서연   34   68000          30대  13600
2  박현우   41   75000          40대  15000
3  최지은   27   48000        20대이하   9600
4  정도윤   36   82000          30대  16400>