<a href="https://colab.research.google.com/github/zzhining/ml_basic/blob/main/pandas_exercise_skeleton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

np.random.seed(0)

# 과제 1
## Q1. 


<div class="alert alert-success">
[문제1]     
    
insurance.csv'파일 읽어서 df에 할당하고, 상위 5개 항목 출력하기
</div>

------------

[힌트]

pd.read_csv()

In [ ]:
import pandas as pd

src_file = r"D:\Practice\hipython\data\insurance.csv"
df = pd.read_csv(src_file)

df.head()
df.info()

## Q2. 


<div class="alert alert-success">
[문제2]     
    
df의 요약(평균, 4분위수, 전체 갯수 등)정보 확인하기
</div>

------------

In [ ]:
print(df['age'].mean(), df['bmi'].mean(), df['charges'].mean())

print('-'*50)
for series in [df['age'], df['bmi'], df['charges']] :
    print (series.name, 'mean :', series.mean())
    print (series.name, 'quantile :', ":")
    print (series.quantile([1/4, 1/2, 3/4]))
    print (series.name, 'stanarde deviation :', series.std())
    print('-'*50)

## Q3. 


<div class="alert alert-success">
[문제3]     
    
신규 컬럼(double bmi)을 생성하고, bmi의 2배가 되는 값을 할당하기
</div>

------------

In [ ]:
df['double bmi'] = [ bmi*2 for bmi in df['bmi']]
df

## Q4. 


<div class="alert alert-success">
[문제4]     
    
신규 컬럼(debt)을 생성하고, 0으로 채우기
</div>

------------

In [ ]:
# df['debt'] = [0] * df.shape[0] 
df['debt'] = 0
df

## Q5. 


<div class="alert alert-success">
[문제5]     
    
debt에 0부터 값이 증가하도록 채우기
</div>

------------

In [ ]:
df['debt'] = range(0, df.shape[0])
df

## Q6. 


<div class="alert alert-success">
[문제6]     
    
1번 인덱스의 정보 출력
</div>

------------

[힌트]
iloc



age                  18  
sex                male  
bmi               33.77  
children              1  
smoker               no  
region        southeast  
charges         1725.55  
double bmi        67.54  
debt                  1

In [ ]:
df.iloc[1]

In [ ]:
df.loc[:, 'age']

## Q7. 


<div class="alert alert-success">
[문제7]     
    
'double bmi'열 삭제하기
</div>

In [ ]:
# axis=1은 열(Column)을 의미합니다.
df = df.drop('double bmi', axis=1) 
# df = df.drop(['double bmi'], axis=1) 

# # 또는 columns 파라미터 사용 (axis 지정 불필요)
# df = df.drop(columns=['열이름'])

## Q8. 


<div class="alert alert-success">
[문제8]     
    
 'age'열, 'sex'열만 출력하기
</div>

In [ ]:
df[['age', 'sex']]

In [ ]:
# df[columns=['age':'bmi']]
df.loc[:, 'age':'bmi']

# 과제2
## Q9.
<div class="alert alert-success">
[문제9]     
    
나이를 1살씩 증가시키기
</div>

In [ ]:
df['age'] += 1
df['age'][1]

## Q10.
<div class="alert alert-success">
[문제10]     
    
charges의 표시형식을 소수점 아래 2자리로 바꾸기
</div>

[힌트]

함수 생성, 적용(apply/map)

In [103]:
df['charges'].map('{:.2f}'.format)

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.94
1337    29141.36
Name: charges, Length: 1338, dtype: object

In [105]:
round(df['charges'], 2)

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.94
1337    29141.36
Name: charges, Length: 1338, dtype: float64

In [ ]:
def round_n(x, n) :
    return round(x, n)

# df['charges'].apply(lambda x : round_n(x, 2))
# df['charges'].map(lambda x : round_n(x, 2))

0       16884.92
1        1725.55
2        4449.46
3       21984.47
4        3866.86
          ...
1333    10600.55
1334     2205.98
1335     1629.83
1336     2007.94
1337    29141.36
Name: charges, Length: 1338, dtype: float64

## Q11.
<div class="alert alert-success">
[문제11]     
    
컬럼 정렬(알파벳 순서대로) : age, bmi, charges... 순으로 정렬
</div>

[Hint]
sort_index()

In [107]:
df = df.sort_index(axis=1)
df

,age,bmi,charges,children,region,sex,sex_01,smoker,smoker_01
0,19,27.900,16884.92400,0,southwest,female,0,yes,1
1,18,33.770,1725.55230,1,southeast,male,1,no,0
2,28,33.000,4449.46200,3,southeast,male,1,no,0
3,33,22.705,21984.47061,0,northwest,male,1,no,0
4,32,28.880,3866.85520,0,northwest,male,1,no,0
...,...,...,...,...,...,...,...,...,...
1333,50,30.970,10600.54830,3,northwest,male,1,no,0
1334,18,31.920,2205.98080,0,northeast,female,0,no,0
1335,18,36.850,1629.83350,0,southeast,female,0,no,0
1336,21,25.800,2007.94500,0,southwest,female,0,no,0
1337,61,29.070,29141.36030,0,northwest,female,0,yes,1

## Q12.
<div class="alert alert-success">
[문제12]     
    
값 정렬(age) : 나이 순으로 정렬
</div>

[Hint]
sort_values

In [ ]:
# df['age'] = df['age'].sort_values() => 다른 열도 같이 바뛰어야 하므로, 한 열만 바꾸는 것은 비정상

df =df.sort_values(by='age')
df

## Q13.
<div class="alert alert-success">
[문제13]     
    
나이('age') 평균구하기
</div>

[Hint]
mean

In [ ]:
df['age'].mean()

## Q14.
<div class="alert alert-success">
[문제14]     
    
보험료('charges')와 가장 상관관계가 높은 변수는?
</div>

[Hint]
 - 공분산: df.cov()
 - 상관계수: df.corr()

In [ ]:
# 남, 여를 0, 1로 벡터화
df['sex_01'] = [1 if sex == 'male' else 0 for sex in df['sex']]
df

In [ ]:
df['smoker_01'] = [1 if smoker == 'yes' else 0 for smoker in df['smoker']]
df

In [ ]:
df[['age', 'sex_01', 'bmi', 'charges', 'children', 'smoker_01']].corr()
# df[['age', 'sex', 'bmi', 'charges', 'smoker']].corr()

In [ ]:
df[['age', 'sex_01','bmi', 'charges', 'children', 'smoker_01']].cov()

# 과제 3
## Q15.
<div class="alert alert-success">
[문제15]     
    
 남자, 여자가 각각 몇명있는지 구하기
</div>

[Hint]
pd.value_counts

In [ ]:
sex_df = df.groupby('sex')
sex_df.size()

In [84]:
df.value_counts('sex')
df['sex'].value_counts()
# pd.value_counts(df['sex']) # depreciated

sex
male      676
female    662
Name: count, dtype: int64

## Q16.
<div class="alert alert-success">
[문제16]     
    
자녀(children)가 3명인 데이터 출력하기
</div>

In [ ]:
df['children']==3 # Boolean Series

In [ ]:
df[df['children']==3]

## Q16.
<div class="alert alert-success">
[문제16]     
    
자녀(children)가  5명 이상인 데이터 출력하기
</div>

In [ ]:
df[df['children']>=5]

## Q17.
<div class="alert alert-success">
[문제17]     
    
 bmi가  17 미만인 데이터 출력하기
</div>

In [ ]:
df[df['bmi']<17]

# 과제 4 
## Q18.
<div class="alert alert-success">
[문제18]     
    
성별에 따른 보험료 평균
</div>

In [ ]:
sex_df = df.groupby('sex')
sex_df.size()

In [ ]:
sex_df.get_group('female')

In [ ]:
sex_df['charges'].mean()

In [ ]:
sex_df['charges'].get_group('female').mean()

## Q19.
<div class="alert alert-success">
[문제19]     
    
흡연여부에 따른 보험료 평균
</div>

In [85]:
sex_df['smoker_01'].mean()

sex
female    0.173716
male      0.235207
Name: smoker_01, dtype: float64

In [86]:
# df['smoker'] = ['yes' if smoker == 1 else 'no' for smoker in df['smoker']]

smoker_df = df.groupby('smoker')
smoker_df.size()

smoker
no     1064
yes     274
dtype: int64

In [87]:
smoker_df['charges'].mean()

smoker
no      8434.268298
yes    32050.231832
Name: charges, dtype: float64

## Q20.
<div class="alert alert-success">
[문제20]     
    
지역별 보험료 평균
</div>

In [ ]:
df.groupby('region')['charges'].mean()

## Q21.
<div class="alert alert-success">
[문제21]     
    
흡연여부 + 지역별 데이터 평균
</div>

In [ ]:
# df.groupby(['region', 'smoker'])['charges'].mean()
# df.groupby('smoker', 'region')['charges'].mean() # Error

df.groupby(['region', 'smoker']).mean(numeric_only=True)

## Q22.
<div class="alert alert-success">
[문제22]     
    
 흡연여부 + 지역별 데이터 평균에서 'charges' 만 츨력하기
</div>

In [ ]:
df.groupby(['smoker', 'region'])['charges'].mean().to_list()

## Q23.
<div class="alert alert-success">
[문제23]     
    
 흡연여부 + 지역별 데이터 크기(size)
</div>

In [ ]:
smoker_region_df = df.groupby(['smoker', 'region'])
smoker_region_df['charges'].size()

## Q24.
<div class="alert alert-success">
[문제24]     
    
smoker 여부에 따라, group_val 컬럼에 '흡연자', '비흡연자' 표시하기
</div>

In [88]:
df['smoker'].map({'yes':'흡연자', 'no':'비흡연자'})

0        흡연자
1       비흡연자
2       비흡연자
3       비흡연자
4       비흡연자
        ...
1333    비흡연자
1334    비흡연자
1335    비흡연자
1336    비흡연자
1337     흡연자
Name: smoker, Length: 1338, dtype: object

In [81]:
df = df.drop(columns=['group_val'])

smoker_region_df.indices.keys()

dict_keys([('no', 'northeast'), ('no', 'northwest'), ('no', 'southeast'), ('no', 'southwest'), ('yes', 'northeast'), ('yes', 'northwest'), ('yes', 'southeast'), ('yes', 'southwest')])

In [89]:
def issmoker(smoker_yn) :
    return '흡연자' if smoker_yn=='yes' else '비흡연자'

df['smoker'].map(issmoker)

0        흡연자
1       비흡연자
2       비흡연자
3       비흡연자
4       비흡연자
        ...
1333    비흡연자
1334    비흡연자
1335    비흡연자
1336    비흡연자
1337     흡연자
Name: smoker, Length: 1338, dtype: object

In [ ]:
group_val = {'smoker':['yes', 'no'], 'smoker_group' : ['흡연자', '비흡연자']}

smoker_group = pd.DataFrame(group_val)
smoker_group

In [94]:
smoke_val = {'yes':'흡연자', 'no':'비흡연자'}

smoke_sr = pd.Series(smoke_val, name='흡연자여부')
smoke_sr

yes     흡연자
no     비흡연자
Name: 흡연자여부, dtype: object

In [95]:
pd.merge(df, smoke_sr, left_on='smoker', right_index=True)

,age,sex,bmi,children,smoker,region,charges,sex_01,smoker_01,흡연자여부
0,19,female,27.900,0,yes,southwest,16884.92400,0,1,흡연자
1,18,male,33.770,1,no,southeast,1725.55230,1,0,비흡연자
2,28,male,33.000,3,no,southeast,4449.46200,1,0,비흡연자
3,33,male,22.705,0,no,northwest,21984.47061,1,0,비흡연자
4,32,male,28.880,0,no,northwest,3866.85520,1,0,비흡연자
...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,1,0,비흡연자
1334,18,female,31.920,0,no,northeast,2205.98080,0,0,비흡연자
1335,18,female,36.850,0,no,southeast,1629.83350,0,0,비흡연자
1336,21,female,25.800,0,no,southwest,2007.94500,0,0,비흡연자
1337,61,female,29.070,0,yes,northwest,29141.36030,0,1,흡연자

In [82]:
pd.merge(df, smoker_group, on='smoker')

,age,sex,bmi,children,smoker,region,charges,sex_01,smoker_01,smoker_group
0,19,female,27.900,0,yes,southwest,16884.92400,0,1,흡연자
1,18,male,33.770,1,no,southeast,1725.55230,1,0,비흡연자
2,28,male,33.000,3,no,southeast,4449.46200,1,0,비흡연자
3,33,male,22.705,0,no,northwest,21984.47061,1,0,비흡연자
4,32,male,28.880,0,no,northwest,3866.85520,1,0,비흡연자
...,...,...,...,...,...,...,...,...,...,...
1333,50,male,30.970,3,no,northwest,10600.54830,1,0,비흡연자
1334,18,female,31.920,0,no,northeast,2205.98080,0,0,비흡연자
1335,18,female,36.850,0,no,southeast,1629.83350,0,0,비흡연자
1336,21,female,25.800,0,no,southwest,2007.94500,0,0,비흡연자
1337,61,female,29.070,0,yes,northwest,29141.36030,0,1,흡연자