In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [ ]:
response = requests.get("https://jsonplaceholder.typicode.com/posts")

print(response.status_code)  # HTTP 상태 코드 출력
print(response.text)         # 응답 본문 출력

print('*'*50)
print(response.json())       # JSON 응답을 파싱하여 출력

df = pd.DataFrame(response.json())
df

# HTML 페이지 연결 : sample.html

Live-Server 웹서비스 구동 후 페이지 보기

In [ ]:
res = requests.get("http://127.0.0.1:5500/WebCrawl/sample.html")
res.text

soup = BeautifulSoup(res.text, 'html.parser')
print(soup.select('h1')[0].text)

print(soup.select('span'))

print('-'*50)
print(soup.select('div'))
print('-'*50)
soup.select('div#subject')  # id로 꺼내기  # => id tag
# soup.select_one('div').text

In [ ]:
soup.select('div.contents')  # class 명으로 꺼내기

HTML 속에 있는 요소를 검색하는 방법

1. 요소를 직접 지정 : find('요소명', id='id명')
2. CSS의 요소를 검색 : select('선택자')

CSS에서
- '#' 은 id, '.'은 class를 나타냄
- 자식은 '>'로 지정 : 'span>b'
- 후손은 공백으로 지정 ' span>a>b>c' => 'span c'
- 클래스속성에 css가 2개 정의되어 있고 두개를 모두 사용하고 싶을 때 '.'으로 나열   
&nbsp;&nbsp;&nbsp;&nbsp;예\) \<div class="head_info point_dn"\> => div.head_info.point_dn    
&nbsp;&nbsp;&nbsp;&nbsp;head_info와 point_dn을 '.'으로 연결

In [ ]:
print(soup.select('div.contents>span>b')[0].text)
soup.select('div>span>b')[0].text
print(soup.select('div>b')[0].text)
print('-'*50)
print(soup.select('div:nth-of-type(2)')[0])

In [ ]:
marketindex = requests.get("https://finance.naver.com/marketindex/")
misoup = BeautifulSoup(marketindex.text, 'html.parser')

In [ ]:
#exchangeList > li.on > a.head.usd > div

usd = float(misoup.select('#exchangeList > li.on > a.head.usd > div > span.value')[0].text.replace(',', ''))
print("USD :", usd)

# JPY
# jpy = float(misoup.select('#worldExchangeList > li.on > a.head.jpy_usd > div > span.value')[0].text)
jpy = float(misoup.select('#worldExchangeList a.head.jpy_usd  span.value')[0].text)
print("JPY :", jpy)


#exchangeList > li:nth-child(2) > a.head.jpy > div > span.value
#worldExchangeList > li.on > a.head.jpy_usd > div > span.value

In [104]:
# YES24 Best Seller List
bestseller_columns = ['rank', 'title', 'author', 'price']    
bestseller_df = pd.DataFrame(columns=bestseller_columns)
    
    
for page in range(1,7) :  # Bestseller top 100
    url =  f"https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber={page}&pageSize=25"
    res = requests.get(url) 
    bestseller_soup = BeautifulSoup(res.text, 'html.parser')
    
    for seq in range(1,26) : 
        selector_rank = f"#yesBestList > li:nth-child({seq}) > div > div.item_img > div.img_canvas > div > em"
        selector_title = f'#yesBestList > li:nth-child({seq}) > div > div.item_info > div.info_row.info_name > a.gd_name'
        selector_price = f"#yesBestList > li:nth-child({seq}) > div > div.item_info > div.info_row.info_price > strong > em"
        selector_author = f"#yesBestList > li:nth-child({seq}) > div > div.item_info > div.info_row.info_pubGrp > span.authPub.info_auth"
        
        book_rank = int(bestseller_soup.select(selector_rank)[0].text)
        book_title = bestseller_soup.select(selector_title)[0].text
        book_author = bestseller_soup.select(selector_author)[0].text.strip()       
        book_price = int(bestseller_soup.select(selector_price)[0].text.replace(',',''))
        
        # bestseller = f"[{book_rank},{book_title},{book_author},{book_price}]"
        bestseller = [book_rank, book_title, book_author, book_price]
        bestseller_df.loc[book_rank] = bestseller
    
        # print(f"Rank {book_rank} : {book_title}, {book_author}, {book_price}원")

bestseller_df = bestseller_df.set_index('rank')

file_name = "yes24_best.csv"
bestseller_df.to_csv(file_name, encoding='utf-8-sig') # 한글깨짐 방지

bestseller_df.head()
bestseller_df.tail()

                                   title          author  price
rank
146                         눈물을 마시는 새 세트           이영도 저  59400
147               된다! 하루 만에 끝내는 제미나이 활용법           권서림 저  18000
148                         데일 카네기 긍정태도론  데일 카네기 저/박선령 역  15210
149                                  명료함          탁민 오 저  17820
150   2026 문동균 한국사 한 권으로 모든 것을 정리하는 판서노트          문동균 편저  15300

In [2]:
class Book :
    def __init__(self, rank, title, author, price):
        self.rank = rank
        self.title = title
        self.author = author
        self.price = price
        
    def __init__(self, book):
        self.rank = book[0]
        self.title = book[1]
        self.author = book[2]
        self.price = book[3]
    
    def __str__(self) :
        return f"{self.rank:03d}: {self.title}, {self.author}, {self.price}원"


# YES24 Best Seller List
bestseller_columns = ['rank', 'title', 'author', 'price']    
bestseller_df = pd.DataFrame(columns=bestseller_columns)
    
    
for page in range(1,7) :  # Bestseller top 100
    url =  f"https://www.yes24.com/product/category/bestseller?categoryNumber=001&pageNumber={page}&pageSize=25"
    res = requests.get(url) 
    bestseller_soup = BeautifulSoup(res.text, 'html.parser')
    
    for seq in range(1,26) : 
        selector_rank = f"#yesBestList > li:nth-child({seq}) > div > div.item_img > div.img_canvas > div > em"
        selector_title = f'#yesBestList > li:nth-child({seq}) > div > div.item_info > div.info_row.info_name > a.gd_name'
        selector_price = f"#yesBestList > li:nth-child({seq}) > div > div.item_info > div.info_row.info_price > strong > em"
        selector_author = f"#yesBestList > li:nth-child({seq}) > div > div.item_info > div.info_row.info_pubGrp > span.authPub.info_auth"
        
        book_rank = int(bestseller_soup.select(selector_rank)[0].text)
        book_title = bestseller_soup.select(selector_title)[0].text
        book_author = bestseller_soup.select(selector_author)[0].text.strip()       
        book_price = int(bestseller_soup.select(selector_price)[0].text.replace(',',''))
        
        # bestseller = f"[{book_rank},{book_title},{book_author},{book_price}]"
        bestseller = [book_rank, book_title, book_author, book_price]
        bsbook = Book(bestseller)
        print(bsbook)
        bestseller_df.loc[book_rank] = bestseller
    
        # print(f"Rank {book_rank} : {book_title}, {book_author}, {book_price}원")

bestseller_df = bestseller_df.set_index('rank')

file_name = "yes24_best.csv"
bestseller_df.to_csv(file_name, encoding='utf-8-sig') # 한글깨짐 방지

bestseller_df.head()
bestseller_df.tail()

001: 나의 완벽한 장례식, 조현선 저, 17100원
002: 진보를 위한 주식투자, 이광수 저, 19800원
003: 박곰희 연금 부자 수업, 박곰희 저, 18900원
004: 괴테는 모든 것을 말했다, 스즈키 유이 저/이지수 역, 15300원
005: ETS 토익 정기시험 기출문제집 1000 Vol. 5 RC, ETS 저, 19800원
006: ETS 토익 정기시험 기출문제집 1000 Vol. 5 LC, ETS 저, 19800원
007: 죽은 왕녀를 위한 파반느 (양장 특별판), 박민규 저, 18000원
008: 자몽살구클럽, 한로로 저, 10800원
009: 2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상, 최태성 저, 17100원
010: 너를 아끼며 살아라, 나태주 저, 16650원
011: 모순, 양귀자 저, 11700원
012: 돈의 방정식, 모건 하우절 저/박영준 역, 25200원
013: 자본주의 시대에서 살아남기 위한 최소한의 경제 공부, 백억남(김욱현) 저, 25200원
014: 1,000만 원으로 3년 안에 300만 원 월배당 만들기, 인생업(임승현) 저, 20700원
015: 위버멘쉬, 프리드리히 니체 저, 16020원
016: 엄마가 유령이 되었어!, 노부미 글그림/이기웅 역, 10800원
017: 안녕이라 그랬어, 김애란 저, 15120원
018: 2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하, 최태성 저, 16650원
019: 최소한의 삼국지, 최태성 저/이성원 감수, 17550원
020: 싯다르타, 헤르만 헤세 저/박병덕 역, 7200원
021: 2026 심우철 실전 동형 모의고사 Season 2, 심우철 저, 13500원
022: 사이토 히토리의 어떻게 살 것인가, 사이토 히토리 저/황미숙 역, 11700원
023: 돈의 심리학 (50만 부 기념 뉴 에디션), 모건 하우절 저/이지연 역, 22320원
024: 더블 클릭, 알간지 저, 17100원
025: 사카모토 데이즈 25 더블특전판, 스즈키 유우토 글그림, 5850원
026: 부처님 말씀대로 살아보니, 토니 페르난도 저/강정선 역, 17010원
027: 캔들차트 하나로 끝내는 추세추종 투자, 성승현 저, 22500원
028: 코스피 1만 넥스트 레벨, 박시동 저, 19800원
029: 혼모노, 성해나 저, 16200원
030: 해커스 토익 기출 VOCA (보카), David Cho 저, 11610원
031: 나의 첫 월배당 ETF, 김정란 저, 19800원
032: 이해찬 회고록, 이해찬 저, 20700원
033: 설민석의 한국사 대모험 36, 설민석, 남이담 글/정현희 그림/강석화 감수, 14400원
034: 코스모스, 칼 에드워드 세이건 저/홍승수 역, 19800원
035: 향기로운 꽃은 늠름하게 핀다 18 더블특전판, 미카미 사카 글그림, 5400원
036: 운명을 보는 기술, 박성준 저, 16920원
037: 교사를 지키는 단단한 학급경영, 이종혁 저, 16200원
038: 어른의 행복은 조용하다, 태수 저, 16020원
039: 2026 써니 행정법총론 실전동형 모의고사, 박준철 편저, 14400원
040: 2026 큰별쌤 최태성의 별별한국사 기출 500제 한국사능력검정시험 심화(1,2,3급), 최태성 저, 19800원
041: 주식투자 무작정 따라하기, 윤재수 저, 22500원
042: 절창 切創, 구병모 저, 16200원
043: 아주 작은 습관의 힘 (50만 부 기념 스페셜 에디션), 제임스 클리어 저/이한이 역, 16200원
044: 2026 문동균 한국사 국가직 대비 실전 봉투 모의고사, 문동균 편저, 11700원
045: 2026 심우철 실전 동형 모의고사 Season 1, 심우철 저, 13500원
046: 내가 돈을 벌고 있다는 착각, commonD 저, 17820원
047: 최소한의 한국사, 최태성 저, 16200원
048: 내 심장을 쏴라, 정유정 저, 16200원
049: 2026 선재국어 결승선 봉투 모의고사, 이선재 편저, 25200원
050: 2026 문동균 한국사 문단속 적중 최종병기 FINAL 모의고사, 문동균 편저, 14400원
051: 내 친구는 왜 그럴까?, 최현주 글/이화경 그림, 15120원
052: 급류, 정대건 저, 12600원
053: 김재우의 기본 동사 100, 김재우 저, 19800원
054: 다크 심리학, 다크 사이드 프로젝트 저, 19710원
055: 해커스 일본어 첫걸음 : 일본어 기초 20일 독학 완성!, 해커스 일본어연구소 저, 12510원
056: SQL 자격검정 실전문제, 한국데이터진흥원 저, 17460원
057: 렛뎀 이론, 멜 로빈스 저/윤효원 역, 18000원
058: 니체의 초월자, 프리드리히 니체 저/김철 편역, 15210원
059: ETS 토익 단기공략 750+ (LC+RC), ETS 저, 17550원
060: 프로젝트 헤일메리 (영화 특별판), 앤디 위어 저/강동혁 역, 19800원
061: 여덟 단어, 박웅현 저, 15300원
062: 데일 카네기 인간관계론 (50만부 돌파 초판 무삭제 완역본), 데일 카네기 저/임상훈 역, 10350원
063: 브람스를 좋아하세요..., 프랑수아즈 사강 저/김남주 역, 9000원
064: 긴긴밤, 루리 글그림, 11250원
065: 블루 아카이브 공식 4컷 청춘? 일상! 블루 아카이브 특별판, 돈미니 저/블루 아카이브 원저, 47700원
066: 2026 문동균 한국사 D-30 문단속 모의고사, 문동균 편저, 14400원
067: 인생을 위한 최소한의 생각, 신영준, 고영성 저, 17820원
068: 오늘 밤, 세계에서 이 사랑이 사라진다 해도, 이치조 미사키 저/권영주 역, 12600원
069: 이게 되네? 제미나이 완전 미친 활용법 81제, 오힘찬 저, 21600원
070: 세이노의 가르침, 세이노(SayNo) 저, 6480원
071: 단다단 19, 타츠 유키노부 글그림, 5400원
072: 우리는 언제나 다시 만나, 윤여림 글/안녕달 그림, 10800원
073: 데미안, 헤르만 헤세 저/전영애 역, 7200원
074: 체인소 맨 22, 후지모토 타츠키 글그림, 5400원
075: 이기적 유전자 The Selfish Gene, 리처드 도킨스 저/홍영남, 이상임 역, 18000원
076: 2026 황철곤 행정학 실전동형 모의고사 SEASON 1, 황철곤 저, 14400원
077: 떠난 것은 돌아오지 않는다, 줄리언 반스 저/정영목 역, 16200원
078: 신뢰 게임, 현순엽, 김진국, 박정식 저, 22000원
079: 너를 미워할 시간에 나를 사랑하기로 했다, 윤서진 저, 16920원
080: 세종의 나라 1, 김진명 저, 19800원
081: 나쁜 일이 있어도 나쁜 날은 아니야, 정문정 글/피도크 그림/천근아 감수, 15120원
082: 부의 인문학 (20만부 기념 개정증보판), 브라운스톤(우석) 저, 15300원
083: 인간 실격, 다자이 오사무 저, 8100원
084: 의사 어벤저스 25, 고희정 글/조승연 그림/류정민 감수, 14220원
085: Again! 뒤집어본 영문법, 오성호 저, 13410원
086: 할매, 황석영 저, 15120원
087: 원피스 ONE PIECE 113, 오다 에이이치로 글그림, 5850원
088: 돈의 속성 400쇄 리커버, 김승호 저, 16020원
089: 쇼펜하우어 인생수업 (30만 부 기념 개정증보판), 쇼펜하우어 저 / 김지민 역, 15750원
090: 소년이 온다, 한강 저, 13500원
091: Go Go 카카오프렌즈 39 칠레, 김미영 글/김정한 그림, 15210원
092: 나는 소망한다 내게 금지된 것을, 양귀자 저, 13500원
093: 2026 심승아 Simple·Detail 소방학개론 심봉사 심승아 봉투 모의고사, 심승아 저, 8100원
094: ETF 투자의 모든 것, 문일호 저, 18900원
095: 편안함의 습격, 마이클 이스터 저/김원진 역, 19800원
096: 일본 광고 카피 도감, 오하림 저, 16920원
097: 세종의 나라 2, 김진명 저, 19800원
098: 최상위권의 생기부, 정성민, 김혜린, 임혁기 저, 40500원
099: 어른의 품격을 채우는 100일 필사 노트, 김종원 저, 18000원
100: 흔한남매 21, 흔한남매 원저/백난도 글/유난희 그림/흔한컴퍼니 감수, 15120원
101: 해커스 보카 Hackers Vocabulary, David Cho 저, 15210원
102: 은애하는 도적님아 대본집 세트, 이선 저, 47700원
103: 해커스 일본어 첫걸음 히라가나 가타카나 쓰기노트, 해커스 일본어연구소 저, 7200원
104: 데일리 필로소피, 라이언 홀리데이, 스티븐 핸슬먼 저/장원철 역, 16200원
105: 쾌적한 사회의 불쾌함, 구마시로 도루 저/이정미 역, 18900원
106: 2026 이유진 국어 백일기도 모의고사 [結(결) 적중], 이유진 편저, 30600원
107: 달러 자산 1억으로 평생 월급 완성하라 (2026 투자 전략 특별판), 채부심(채상욱) 저, 18900원
108: 행복할 거야 이래도 되나 싶을 정도로, 일홍 저, 16200원
109: 기적의 초등 신문 2026, 강버들, 민경원, 이유정, 채윤경, 임소연 글, 17820원
110: 2026 선재국어 출발선 봉투 모의고사, 이선재 편저, 25200원
111: 부모는 가장 좋은 입시 멘토다, 박성오 저, 16920원
112: 1984, 조지 오웰 저/정회성 역, 9900원
113: 2026 유휘운 행정법총론 실전동형 모의고사, 유휘운 편저, 9900원
114: 절대수익 우량주 매매법, 성경호 저, 35100원
115: 규칙파괴자, 데이비드 가드너 저/김태훈 역, 22500원
116: 하루 한 장 나의 어휘력을 위한 필사 노트, 유선경 저, 21420원
117: 스킵과 로퍼 11 더블 특전판, 타카마츠 미사키 글그림/신혜선 역, 5400원
118: ETS 토익기출 파트별 VOCA 보카, ETS 저, 11700원
119: 어른의 그릇, 조윤제 저, 17100원
120: 이방인, 알베르 까뮈 저/김화영 역, 9000원
121: 2026 이유진 국어 백일기도 모의고사 [承(승)_시간단축], 이유진 편저, 25200원
122: 정답은 있다, 이정효 저, 16200원
123: 뇌는 어떻게 나를 조종하는가, 크리스 나이바우어 저/김윤종 역, 16920원
124: 새들이 전하는 짧은 철학, 필리프 J. 뒤부아, 엘리즈 루소 저/박효은 역, 15300원
125: 2026 이유진 국어 백일기도 모의고사 [轉(전) 극한훈련], 이유진 편저, 25200원
126: 눈과 돌멩이, 위수정, 김혜진, 성혜령, 이민진, 정이현 저 외 1명

정보 더 보기/감추기



위수정
김혜진
성혜령
이민진
정이현
함윤이, 16200원
127: 어머니의 집밥을 먹을 수 있는 횟수는 328번 남았습니다, 우와노 소라 저/박춘상 역, 15120원
128: 반짝반짝 1학년, 학교는 널 기다려!, 전영신 글/근홍 그림, 13050원
129: 손자병법, 손자 저/소준섭 역, 11700원
130: 김재우의 기초 영어회화 100, 김재우 저, 17010원
131: 메이지의 영원한 삶을 위해, 크리스토퍼 엣지 글/민지현 역, 11700원
132: 존리의 부자되기 습관, 존리 저, 18000원
133: 해커스 토익 RC Reading(리딩) 기본서, David Cho 저, 16920원
134: 비실비실 선생님 11, 후쿠치 카미오 글그림, 5400원
135: 초판본 데미안, 헤르만 헤세 저/이순학 역, 1980원
136: AI 시대 십 대를 위한 논어, 최태규 저, 16920원
137: 총 균 쇠, 재레드 다이아몬드 저/강주헌 역, 26820원
138: 두근두근 1학년, 우리는 널 사랑해!, 전영신 글/근홍 그림, 13050원
139: 몬스터 캠핑장, 정주영 글/김현민 그림, 12600원
140: 말뚝들, 김홍 저, 15120원
141: 어린이 같은 말 다른 뜻 사전, 박세랑 글그림, 16020원
142: 2026 위포트 공기업 NCS 통합기본서 (PSAT형+모듈형+피듈형+실전 모의고사), 위포트 연구소 저, 24300원
143: 기분이 태도가 되지 않게 (헬로키티 에디션), 레몬심리 저/박영란 역, 16200원
144: 불변의 법칙, 모건 하우절 저/이수경 역, 22500원
145: 오래된 세계의 농담, 이다혜 저, 16200원
146: 눈물을 마시는 새 세트, 이영도 저, 59400원
147: 된다! 하루 만에 끝내는 제미나이 활용법, 권서림 저, 18000원
148: 데일 카네기 긍정태도론, 데일 카네기 저/박선령 역, 15210원
149: 명료함, 탁민 오 저, 17820원
150: 2026 문동균 한국사 한 권으로 모든 것을 정리하는 판서노트, 문동균 편저, 15300원

                                   title          author  price
rank
146                         눈물을 마시는 새 세트           이영도 저  59400
147               된다! 하루 만에 끝내는 제미나이 활용법           권서림 저  18000
148                         데일 카네기 긍정태도론  데일 카네기 저/박선령 역  15210
149                                  명료함          탁민 오 저  17820
150   2026 문동균 한국사 한 권으로 모든 것을 정리하는 판서노트          문동균 편저  15300

In [107]:
import sqlite3

conn = sqlite3.connect('_books.db')
cursor = conn.cursor()

# 테이블 생성
create_query = '''  
CREATE TABLE IF NOT EXISTS books (
    rank INTEGER PRIMARY KEY,
    title TEXT,
    author TEXT,
    price INTEGER
)
'''
cursor.execute(create_query)

conn.commit()
cursor.close()
conn.close()

In [105]:
for index, row in bestseller_df.iterrows():
    print(f"인덱스: {index}")
    print(f"이름: {row['title']}, 나이: {row['author']}")

인덱스: 1
이름: 나의 완벽한 장례식, 나이: 조현선 저
인덱스: 2
이름: 진보를 위한 주식투자, 나이: 이광수 저
인덱스: 3
이름: 박곰희 연금 부자 수업, 나이: 박곰희 저
인덱스: 4
이름: 괴테는 모든 것을 말했다, 나이: 스즈키 유이 저/이지수 역
인덱스: 5
이름: ETS 토익 정기시험 기출문제집 1000 Vol. 5 RC, 나이: ETS 저
인덱스: 6
이름: ETS 토익 정기시험 기출문제집 1000 Vol. 5 LC, 나이: ETS 저
인덱스: 7
이름: 죽은 왕녀를 위한 파반느 (양장 특별판), 나이: 박민규 저
인덱스: 8
이름: 자몽살구클럽, 나이: 한로로 저
인덱스: 9
이름: 2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상, 나이: 최태성 저
인덱스: 10
이름: 너를 아끼며 살아라, 나이: 나태주 저
인덱스: 11
이름: 모순, 나이: 양귀자 저
인덱스: 12
이름: 돈의 방정식, 나이: 모건 하우절 저/박영준 역
인덱스: 13
이름: 자본주의 시대에서 살아남기 위한 최소한의 경제 공부, 나이: 백억남(김욱현) 저
인덱스: 14
이름: 1,000만 원으로 3년 안에 300만 원 월배당 만들기, 나이: 인생업(임승현) 저
인덱스: 15
이름: 위버멘쉬, 나이: 프리드리히 니체 저
인덱스: 16
이름: 엄마가 유령이 되었어!, 나이: 노부미 글그림/이기웅 역
인덱스: 17
이름: 안녕이라 그랬어, 나이: 김애란 저
인덱스: 18
이름: 2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하, 나이: 최태성 저
인덱스: 19
이름: 최소한의 삼국지, 나이: 최태성 저/이성원 감수
인덱스: 20
이름: 싯다르타, 나이: 헤르만 헤세 저/박병덕 역
인덱스: 21
이름: 2026 심우철 실전 동형 모의고사 Season 2, 나이: 심우철 저
인덱스: 22
이름: 사이토 히토리의 어떻게 살 것인가, 나이: 사이토 히토리 저/황미숙 역
인덱스: 23
이름: 돈의 심리학 (50만 부 기념 뉴 에디션), 나이: 모건 하우절 저/이지연 역
인덱스: 24
이름: 더블 클릭, 나이: 알간지 저
인덱스: 25
이름: 사카모토 데이즈 25 더블특전판, 나이: 스즈키 유우토 글그림
인덱스: 26
이름: 부처님 말씀대로 살아보니, 나이: 토니 페르난도 저/강정선 역
인덱스: 27
이름: 캔들차트 하나로 끝내는 추세추종 투자, 나이: 성승현 저
인덱스: 28
이름: 코스피 1만 넥스트 레벨, 나이: 박시동 저
인덱스: 29
이름: 혼모노, 나이: 성해나 저
인덱스: 30
이름: 해커스 토익 기출 VOCA (보카), 나이: David Cho 저
인덱스: 31
이름: 나의 첫 월배당 ETF, 나이: 김정란 저
인덱스: 32
이름: 이해찬 회고록, 나이: 이해찬 저
인덱스: 33
이름: 설민석의 한국사 대모험 36, 나이: 설민석, 남이담 글/정현희 그림/강석화 감수
인덱스: 34
이름: 코스모스, 나이: 칼 에드워드 세이건 저/홍승수 역
인덱스: 35
이름: 향기로운 꽃은 늠름하게 핀다 18 더블특전판, 나이: 미카미 사카 글그림
인덱스: 36
이름: 운명을 보는 기술, 나이: 박성준 저
인덱스: 37
이름: 교사를 지키는 단단한 학급경영, 나이: 이종혁 저
인덱스: 38
이름: 어른의 행복은 조용하다, 나이: 태수 저
인덱스: 39
이름: 2026 써니 행정법총론 실전동형 모의고사, 나이: 박준철 편저
인덱스: 40
이름: 2026 큰별쌤 최태성의 별별한국사 기출 500제 한국사능력검정시험 심화(1,2,3급), 나이: 최태성 저
인덱스: 41
이름: 주식투자 무작정 따라하기, 나이: 윤재수 저
인덱스: 42
이름: 절창 切創, 나이: 구병모 저
인덱스: 43
이름: 아주 작은 습관의 힘 (50만 부 기념 스페셜 에디션), 나이: 제임스 클리어 저/이한이 역
인덱스: 44
이름: 2026 문동균 한국사 국가직 대비 실전 봉투 모의고사, 나이: 문동균 편저
인덱스: 45
이름: 2026 심우철 실전 동형 모의고사 Season 1, 나이: 심우철 저
인덱스: 46
이름: 내가 돈을 벌고 있다는 착각, 나이: commonD 저
인덱스: 47
이름: 최소한의 한국사, 나이: 최태성 저
인덱스: 48
이름: 내 심장을 쏴라, 나이: 정유정 저
인덱스: 49
이름: 2026 선재국어 결승선 봉투 모의고사, 나이: 이선재 편저
인덱스: 50
이름: 2026 문동균 한국사 문단속 적중 최종병기 FINAL 모의고사, 나이: 문동균 편저
인덱스: 51
이름: 내 친구는 왜 그럴까?, 나이: 최현주 글/이화경 그림
인덱스: 52
이름: 급류, 나이: 정대건 저
인덱스: 53
이름: 김재우의 기본 동사 100, 나이: 김재우 저
인덱스: 54
이름: 다크 심리학, 나이: 다크 사이드 프로젝트 저
인덱스: 55
이름: 해커스 일본어 첫걸음 : 일본어 기초 20일 독학 완성!, 나이: 해커스 일본어연구소 저
인덱스: 56
이름: SQL 자격검정 실전문제, 나이: 한국데이터진흥원 저
인덱스: 57
이름: 렛뎀 이론, 나이: 멜 로빈스 저/윤효원 역
인덱스: 58
이름: 니체의 초월자, 나이: 프리드리히 니체 저/김철 편역
인덱스: 59
이름: ETS 토익 단기공략 750+ (LC+RC), 나이: ETS 저
인덱스: 60
이름: 프로젝트 헤일메리 (영화 특별판), 나이: 앤디 위어 저/강동혁 역
인덱스: 61
이름: 여덟 단어, 나이: 박웅현 저
인덱스: 62
이름: 데일 카네기 인간관계론 (50만부 돌파 초판 무삭제 완역본), 나이: 데일 카네기 저/임상훈 역
인덱스: 63
이름: 브람스를 좋아하세요..., 나이: 프랑수아즈 사강 저/김남주 역
인덱스: 64
이름: 긴긴밤, 나이: 루리 글그림
인덱스: 65
이름: 블루 아카이브 공식 4컷 청춘? 일상! 블루 아카이브 특별판, 나이: 돈미니 저/블루 아카이브 원저
인덱스: 66
이름: 2026 문동균 한국사 D-30 문단속 모의고사, 나이: 문동균 편저
인덱스: 67
이름: 인생을 위한 최소한의 생각, 나이: 신영준, 고영성 저
인덱스: 68
이름: 오늘 밤, 세계에서 이 사랑이 사라진다 해도, 나이: 이치조 미사키 저/권영주 역
인덱스: 69
이름: 이게 되네? 제미나이 완전 미친 활용법 81제, 나이: 오힘찬 저
인덱스: 70
이름: 세이노의 가르침, 나이: 세이노(SayNo) 저
인덱스: 71
이름: 단다단 19, 나이: 타츠 유키노부 글그림
인덱스: 72
이름: 우리는 언제나 다시 만나, 나이: 윤여림 글/안녕달 그림
인덱스: 73
이름: 데미안, 나이: 헤르만 헤세 저/전영애 역
인덱스: 74
이름: 체인소 맨 22, 나이: 후지모토 타츠키 글그림
인덱스: 75
이름: 이기적 유전자 The Selfish Gene, 나이: 리처드 도킨스 저/홍영남, 이상임 역
인덱스: 76
이름: 2026 황철곤 행정학 실전동형 모의고사 SEASON 1, 나이: 황철곤 저
인덱스: 77
이름: 떠난 것은 돌아오지 않는다, 나이: 줄리언 반스 저/정영목 역
인덱스: 78
이름: 신뢰 게임, 나이: 현순엽, 김진국, 박정식 저
인덱스: 79
이름: 너를 미워할 시간에 나를 사랑하기로 했다, 나이: 윤서진 저
인덱스: 80
이름: 세종의 나라 1, 나이: 김진명 저
인덱스: 81
이름: 나쁜 일이 있어도 나쁜 날은 아니야, 나이: 정문정 글/피도크 그림/천근아 감수
인덱스: 82
이름: 부의 인문학 (20만부 기념 개정증보판), 나이: 브라운스톤(우석) 저
인덱스: 83
이름: 인간 실격, 나이: 다자이 오사무 저
인덱스: 84
이름: 의사 어벤저스 25, 나이: 고희정 글/조승연 그림/류정민 감수
인덱스: 85
이름: Again! 뒤집어본 영문법, 나이: 오성호 저
인덱스: 86
이름: 할매, 나이: 황석영 저
인덱스: 87
이름: 원피스 ONE PIECE 113, 나이: 오다 에이이치로 글그림
인덱스: 88
이름: 돈의 속성 400쇄 리커버, 나이: 김승호 저
인덱스: 89
이름: 쇼펜하우어 인생수업 (30만 부 기념 개정증보판), 나이: 쇼펜하우어 저 / 김지민 역
인덱스: 90
이름: 소년이 온다, 나이: 한강 저
인덱스: 91
이름: Go Go 카카오프렌즈 39 칠레, 나이: 김미영 글/김정한 그림
인덱스: 92
이름: 나는 소망한다 내게 금지된 것을, 나이: 양귀자 저
인덱스: 93
이름: 2026 심승아 Simple·Detail 소방학개론 심봉사 심승아 봉투 모의고사, 나이: 심승아 저
인덱스: 94
이름: ETF 투자의 모든 것, 나이: 문일호 저
인덱스: 95
이름: 편안함의 습격, 나이: 마이클 이스터 저/김원진 역
인덱스: 96
이름: 일본 광고 카피 도감, 나이: 오하림 저
인덱스: 97
이름: 세종의 나라 2, 나이: 김진명 저
인덱스: 98
이름: 최상위권의 생기부, 나이: 정성민, 김혜린, 임혁기 저
인덱스: 99
이름: 어른의 품격을 채우는 100일 필사 노트, 나이: 김종원 저
인덱스: 100
이름: 흔한남매 21, 나이: 흔한남매 원저/백난도 글/유난희 그림/흔한컴퍼니 감수
인덱스: 101
이름: 해커스 보카 Hackers Vocabulary, 나이: David Cho 저
인덱스: 102
이름: 은애하는 도적님아 대본집 세트, 나이: 이선 저
인덱스: 103
이름: 해커스 일본어 첫걸음 히라가나 가타카나 쓰기노트, 나이: 해커스 일본어연구소 저
인덱스: 104
이름: 데일리 필로소피, 나이: 라이언 홀리데이, 스티븐 핸슬먼 저/장원철 역
인덱스: 105
이름: 쾌적한 사회의 불쾌함, 나이: 구마시로 도루 저/이정미 역
인덱스: 106
이름: 2026 이유진 국어 백일기도 모의고사 [結(결) 적중], 나이: 이유진 편저
인덱스: 107
이름: 달러 자산 1억으로 평생 월급 완성하라 (2026 투자 전략 특별판), 나이: 채부심(채상욱) 저
인덱스: 108
이름: 행복할 거야 이래도 되나 싶을 정도로, 나이: 일홍 저
인덱스: 109
이름: 기적의 초등 신문 2026, 나이: 강버들, 민경원, 이유정, 채윤경, 임소연 글
인덱스: 110
이름: 2026 선재국어 출발선 봉투 모의고사, 나이: 이선재 편저
인덱스: 111
이름: 부모는 가장 좋은 입시 멘토다, 나이: 박성오 저
인덱스: 112
이름: 1984, 나이: 조지 오웰 저/정회성 역
인덱스: 113
이름: 2026 유휘운 행정법총론 실전동형 모의고사, 나이: 유휘운 편저
인덱스: 114
이름: 절대수익 우량주 매매법, 나이: 성경호 저
인덱스: 115
이름: 규칙파괴자, 나이: 데이비드 가드너 저/김태훈 역
인덱스: 116
이름: 하루 한 장 나의 어휘력을 위한 필사 노트, 나이: 유선경 저
인덱스: 117
이름: 스킵과 로퍼 11 더블 특전판, 나이: 타카마츠 미사키 글그림/신혜선 역
인덱스: 118
이름: ETS 토익기출 파트별 VOCA 보카, 나이: ETS 저
인덱스: 119
이름: 어른의 그릇, 나이: 조윤제 저
인덱스: 120
이름: 이방인, 나이: 알베르 까뮈 저/김화영 역
인덱스: 121
이름: 2026 이유진 국어 백일기도 모의고사 [承(승)_시간단축], 나이: 이유진 편저
인덱스: 122
이름: 정답은 있다, 나이: 이정효 저
인덱스: 123
이름: 뇌는 어떻게 나를 조종하는가, 나이: 크리스 나이바우어 저/김윤종 역
인덱스: 124
이름: 새들이 전하는 짧은 철학, 나이: 필리프 J. 뒤부아, 엘리즈 루소 저/박효은 역
인덱스: 125
이름: 2026 이유진 국어 백일기도 모의고사 [轉(전) 극한훈련], 나이: 이유진 편저
인덱스: 126
이름: 눈과 돌멩이, 나이: 위수정, 김혜진, 성혜령, 이민진, 정이현 저 외 1명

정보 더 보기/감추기



위수정
김혜진
성혜령
이민진
정이현
함윤이
인덱스: 127
이름: 어머니의 집밥을 먹을 수 있는 횟수는 328번 남았습니다, 나이: 우와노 소라 저/박춘상 역
인덱스: 128
이름: 반짝반짝 1학년, 학교는 널 기다려!, 나이: 전영신 글/근홍 그림
인덱스: 129
이름: 손자병법, 나이: 손자 저/소준섭 역
인덱스: 130
이름: 김재우의 기초 영어회화 100, 나이: 김재우 저
인덱스: 131
이름: 메이지의 영원한 삶을 위해, 나이: 크리스토퍼 엣지 글/민지현 역
인덱스: 132
이름: 존리의 부자되기 습관, 나이: 존리 저
인덱스: 133
이름: 해커스 토익 RC Reading(리딩) 기본서, 나이: David Cho 저
인덱스: 134
이름: 비실비실 선생님 11, 나이: 후쿠치 카미오 글그림
인덱스: 135
이름: 초판본 데미안, 나이: 헤르만 헤세 저/이순학 역
인덱스: 136
이름: AI 시대 십 대를 위한 논어, 나이: 최태규 저
인덱스: 137
이름: 총 균 쇠, 나이: 재레드 다이아몬드 저/강주헌 역
인덱스: 138
이름: 두근두근 1학년, 우리는 널 사랑해!, 나이: 전영신 글/근홍 그림
인덱스: 139
이름: 몬스터 캠핑장, 나이: 정주영 글/김현민 그림
인덱스: 140
이름: 말뚝들, 나이: 김홍 저
인덱스: 141
이름: 어린이 같은 말 다른 뜻 사전, 나이: 박세랑 글그림
인덱스: 142
이름: 2026 위포트 공기업 NCS 통합기본서 (PSAT형+모듈형+피듈형+실전 모의고사), 나이: 위포트 연구소 저
인덱스: 143
이름: 기분이 태도가 되지 않게 (헬로키티 에디션), 나이: 레몬심리 저/박영란 역
인덱스: 144
이름: 불변의 법칙, 나이: 모건 하우절 저/이수경 역
인덱스: 145
이름: 오래된 세계의 농담, 나이: 이다혜 저
인덱스: 146
이름: 눈물을 마시는 새 세트, 나이: 이영도 저
인덱스: 147
이름: 된다! 하루 만에 끝내는 제미나이 활용법, 나이: 권서림 저
인덱스: 148
이름: 데일 카네기 긍정태도론, 나이: 데일 카네기 저/박선령 역
인덱스: 149
이름: 명료함, 나이: 탁민 오 저
인덱스: 150
이름: 2026 문동균 한국사 한 권으로 모든 것을 정리하는 판서노트, 나이: 문동균 편저

In [ ]:
import sqlite3

conn = sqlite3.connect('_books.db')
cursor = conn.cursor()

# 데이터 삽입
insert_sql = "INSERT INTO books (rank, title, author, price) VALUES (?, ?, ?, ?)"

for index, book in bestseller_df.iterrows():
    cursor.execute(insert_sql, (index, book['title'], book['author'][:100], book['price']))

conn.commit()
cursor.close()
conn.close()

In [109]:
conn = sqlite3.connect('_books.db')
cursor = conn.cursor()

# 데이터 조회
cursor.execute('SELECT * FROM books')
rows = cursor.fetchall()
for row in rows:
    print(row)
    
cursor.close()
conn.close()

(1, '나의 완벽한 장례식', '조현선 저', 17100)
(2, '진보를 위한 주식투자', '이광수 저', 19800)
(3, '박곰희 연금 부자 수업', '박곰희 저', 18900)
(4, '괴테는 모든 것을 말했다', '스즈키 유이 저/이지수 역', 15300)
(5, 'ETS 토익 정기시험 기출문제집 1000 Vol. 5 RC', 'ETS 저', 19800)
(6, 'ETS 토익 정기시험 기출문제집 1000 Vol. 5 LC', 'ETS 저', 19800)
(7, '죽은 왕녀를 위한 파반느 (양장 특별판)', '박민규 저', 18000)
(8, '자몽살구클럽', '한로로 저', 10800)
(9, '2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상', '최태성 저', 17100)
(10, '너를 아끼며 살아라', '나태주 저', 16650)
(11, '모순', '양귀자 저', 11700)
(12, '돈의 방정식', '모건 하우절 저/박영준 역', 25200)
(13, '자본주의 시대에서 살아남기 위한 최소한의 경제 공부', '백억남(김욱현) 저', 25200)
(14, '1,000만 원으로 3년 안에 300만 원 월배당 만들기', '인생업(임승현) 저', 20700)
(15, '위버멘쉬', '프리드리히 니체 저', 16020)
(16, '엄마가 유령이 되었어!', '노부미 글그림/이기웅 역', 10800)
(17, '안녕이라 그랬어', '김애란 저', 15120)
(18, '2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하', '최태성 저', 16650)
(19, '최소한의 삼국지', '최태성 저/이성원 감수', 17550)
(20, '싯다르타', '헤르만 헤세 저/박병덕 역', 7200)
(21, '2026 심우철 실전 동형 모의고사 Season 2', '심우철 저', 13500)
(22, '사이토 히토리의 어떻게 살 것인가', '사이토 히토리 저/황미숙 역', 11700)
(23, '돈의 심리학 (50만 부 기념 뉴 에디션)', '모건 하우절 저/이지연 역', 22320)
(24, '더블 클릭', '알간지 저', 17100)
(25, '사카모토 데이즈 25 더블특전판', '스즈키 유우토 글그림', 5850)
(26, '부처님 말씀대로 살아보니', '토니 페르난도 저/강정선 역', 17010)
(27, '캔들차트 하나로 끝내는 추세추종 투자', '성승현 저', 22500)
(28, '코스피 1만 넥스트 레벨', '박시동 저', 19800)
(29, '혼모노', '성해나 저', 16200)
(30, '해커스 토익 기출 VOCA (보카)', 'David Cho 저', 11610)
(31, '나의 첫 월배당 ETF', '김정란 저', 19800)
(32, '이해찬 회고록', '이해찬 저', 20700)
(33, '설민석의 한국사 대모험 36', '설민석, 남이담 글/정현희 그림/강석화 감수', 14400)
(34, '코스모스', '칼 에드워드 세이건 저/홍승수 역', 19800)
(35, '향기로운 꽃은 늠름하게 핀다 18 더블특전판', '미카미 사카 글그림', 5400)
(36, '운명을 보는 기술', '박성준 저', 16920)
(37, '교사를 지키는 단단한 학급경영', '이종혁 저', 16200)
(38, '어른의 행복은 조용하다', '태수 저', 16020)
(39, '2026 써니 행정법총론 실전동형 모의고사', '박준철 편저', 14400)
(40, '2026 큰별쌤 최태성의 별별한국사 기출 500제 한국사능력검정시험 심화(1,2,3급)', '최태성 저', 19800)
(41, '주식투자 무작정 따라하기', '윤재수 저', 22500)
(42, '절창 切創', '구병모 저', 16200)
(43, '아주 작은 습관의 힘 (50만 부 기념 스페셜 에디션)', '제임스 클리어 저/이한이 역', 16200)
(44, '2026 문동균 한국사 국가직 대비 실전 봉투 모의고사', '문동균 편저', 11700)
(45, '2026 심우철 실전 동형 모의고사 Season 1', '심우철 저', 13500)
(46, '내가 돈을 벌고 있다는 착각', 'commonD 저', 17820)
(47, '최소한의 한국사', '최태성 저', 16200)
(48, '내 심장을 쏴라', '정유정 저', 16200)
(49, '2026 선재국어 결승선 봉투 모의고사', '이선재 편저', 25200)
(50, '2026 문동균 한국사 문단속 적중 최종병기 FINAL 모의고사', '문동균 편저', 14400)
(51, '내 친구는 왜 그럴까?', '최현주 글/이화경 그림', 15120)
(52, '급류', '정대건 저', 12600)
(53, '김재우의 기본 동사 100', '김재우 저', 19800)
(54, '다크 심리학', '다크 사이드 프로젝트 저', 19710)
(55, '해커스 일본어 첫걸음 : 일본어 기초 20일 독학 완성!', '해커스 일본어연구소 저', 12510)
(56, 'SQL 자격검정 실전문제', '한국데이터진흥원 저', 17460)
(57, '렛뎀 이론', '멜 로빈스 저/윤효원 역', 18000)
(58, '니체의 초월자', '프리드리히 니체 저/김철 편역', 15210)
(59, 'ETS 토익 단기공략 750+ (LC+RC)', 'ETS 저', 17550)
(60, '프로젝트 헤일메리 (영화 특별판)', '앤디 위어 저/강동혁 역', 19800)
(61, '여덟 단어', '박웅현 저', 15300)
(62, '데일 카네기 인간관계론 (50만부 돌파 초판 무삭제 완역본)', '데일 카네기 저/임상훈 역', 10350)
(63, '브람스를 좋아하세요...', '프랑수아즈 사강 저/김남주 역', 9000)
(64, '긴긴밤', '루리 글그림', 11250)
(65, '블루 아카이브 공식 4컷 청춘? 일상! 블루 아카이브 특별판', '돈미니 저/블루 아카이브 원저', 47700)
(66, '2026 문동균 한국사 D-30 문단속 모의고사', '문동균 편저', 14400)
(67, '인생을 위한 최소한의 생각', '신영준, 고영성 저', 17820)
(68, '오늘 밤, 세계에서 이 사랑이 사라진다 해도', '이치조 미사키 저/권영주 역', 12600)
(69, '이게 되네? 제미나이 완전 미친 활용법 81제', '오힘찬 저', 21600)
(70, '세이노의 가르침', '세이노(SayNo) 저', 6480)
(71, '단다단 19', '타츠 유키노부 글그림', 5400)
(72, '우리는 언제나 다시 만나', '윤여림 글/안녕달 그림', 10800)
(73, '데미안', '헤르만 헤세 저/전영애 역', 7200)
(74, '체인소 맨 22', '후지모토 타츠키 글그림', 5400)
(75, '이기적 유전자 The Selfish Gene', '리처드 도킨스 저/홍영남, 이상임 역', 18000)
(76, '2026 황철곤 행정학 실전동형 모의고사 SEASON 1', '황철곤 저', 14400)
(77, '떠난 것은 돌아오지 않는다', '줄리언 반스 저/정영목 역', 16200)
(78, '신뢰 게임', '현순엽, 김진국, 박정식 저', 22000)
(79, '너를 미워할 시간에 나를 사랑하기로 했다', '윤서진 저', 16920)
(80, '세종의 나라 1', '김진명 저', 19800)
(81, '나쁜 일이 있어도 나쁜 날은 아니야', '정문정 글/피도크 그림/천근아 감수', 15120)
(82, '부의 인문학 (20만부 기념 개정증보판)', '브라운스톤(우석) 저', 15300)
(83, '인간 실격', '다자이 오사무 저', 8100)
(84, '의사 어벤저스 25', '고희정 글/조승연 그림/류정민 감수', 14220)
(85, 'Again! 뒤집어본 영문법', '오성호 저', 13410)
(86, '할매', '황석영 저', 15120)
(87, '원피스 ONE PIECE 113', '오다 에이이치로 글그림', 5850)
(88, '돈의 속성 400쇄 리커버', '김승호 저', 16020)
(89, '쇼펜하우어 인생수업 (30만 부 기념 개정증보판)', '쇼펜하우어 저 / 김지민 역', 15750)
(90, '소년이 온다', '한강 저', 13500)
(91, 'Go Go 카카오프렌즈 39 칠레', '김미영 글/김정한 그림', 15210)
(92, '나는 소망한다 내게 금지된 것을', '양귀자 저', 13500)
(93, '2026 심승아 Simple·Detail 소방학개론 심봉사 심승아 봉투 모의고사', '심승아 저', 8100)
(94, 'ETF 투자의 모든 것', '문일호 저', 18900)
(95, '편안함의 습격', '마이클 이스터 저/김원진 역', 19800)
(96, '일본 광고 카피 도감', '오하림 저', 16920)
(97, '세종의 나라 2', '김진명 저', 19800)
(98, '최상위권의 생기부', '정성민, 김혜린, 임혁기 저', 40500)
(99, '어른의 품격을 채우는 100일 필사 노트', '김종원 저', 18000)
(100, '흔한남매 21', '흔한남매 원저/백난도 글/유난희 그림/흔한컴퍼니 감수', 15120)
(101, '해커스 보카 Hackers Vocabulary', 'David Cho 저', 15210)
(102, '은애하는 도적님아 대본집 세트', '이선 저', 47700)
(103, '해커스 일본어 첫걸음 히라가나 가타카나 쓰기노트', '해커스 일본어연구소 저', 7200)
(104, '데일리 필로소피', '라이언 홀리데이, 스티븐 핸슬먼 저/장원철 역', 16200)
(105, '쾌적한 사회의 불쾌함', '구마시로 도루 저/이정미 역', 18900)
(106, '2026 이유진 국어 백일기도 모의고사 [結(결) 적중]', '이유진 편저', 30600)
(107, '달러 자산 1억으로 평생 월급 완성하라 (2026 투자 전략 특별판)', '채부심(채상욱) 저', 18900)
(108, '행복할 거야 이래도 되나 싶을 정도로', '일홍 저', 16200)
(109, '기적의 초등 신문 2026', '강버들, 민경원, 이유정, 채윤경, 임소연 글', 17820)
(110, '2026 선재국어 출발선 봉투 모의고사', '이선재 편저', 25200)
(111, '부모는 가장 좋은 입시 멘토다', '박성오 저', 16920)
(112, '1984', '조지 오웰 저/정회성 역', 9900)
(113, '2026 유휘운 행정법총론 실전동형 모의고사', '유휘운 편저', 9900)
(114, '절대수익 우량주 매매법', '성경호 저', 35100)
(115, '규칙파괴자', '데이비드 가드너 저/김태훈 역', 22500)
(116, '하루 한 장 나의 어휘력을 위한 필사 노트', '유선경 저', 21420)
(117, '스킵과 로퍼 11 더블 특전판', '타카마츠 미사키 글그림/신혜선 역', 5400)
(118, 'ETS 토익기출 파트별 VOCA 보카', 'ETS 저', 11700)
(119, '어른의 그릇', '조윤제 저', 17100)
(120, '이방인', '알베르 까뮈 저/김화영 역', 9000)
(121, '2026 이유진 국어 백일기도 모의고사 [承(승)_시간단축]', '이유진 편저', 25200)
(122, '정답은 있다', '이정효 저', 16200)
(123, '뇌는 어떻게 나를 조종하는가', '크리스 나이바우어 저/김윤종 역', 16920)
(124, '새들이 전하는 짧은 철학', '필리프 J. 뒤부아, 엘리즈 루소 저/박효은 역', 15300)
(125, '2026 이유진 국어 백일기도 모의고사 [轉(전) 극한훈련]', '이유진 편저', 25200)
(126, '눈과 돌멩이', '위수정, 김혜진, 성혜령, 이민진, 정이현 저 외 1명\r\n                                        \n정보 더 보기/감추기\n\n\n\n위수정\n김혜진\n성혜령\n이민진\n정이현\n함윤이', 16200)
(127, '어머니의 집밥을 먹을 수 있는 횟수는 328번 남았습니다', '우와노 소라 저/박춘상 역', 15120)
(128, '반짝반짝 1학년, 학교는 널 기다려!', '전영신 글/근홍 그림', 13050)
(129, '손자병법', '손자 저/소준섭 역', 11700)
(130, '김재우의 기초 영어회화 100', '김재우 저', 17010)
(131, '메이지의 영원한 삶을 위해', '크리스토퍼 엣지 글/민지현 역', 11700)
(132, '존리의 부자되기 습관', '존리 저', 18000)
(133, '해커스 토익 RC Reading(리딩) 기본서', 'David Cho 저', 16920)
(134, '비실비실 선생님 11', '후쿠치 카미오 글그림', 5400)
(135, '초판본 데미안', '헤르만 헤세 저/이순학 역', 1980)
(136, 'AI 시대 십 대를 위한 논어', '최태규 저', 16920)
(137, '총 균 쇠', '재레드 다이아몬드 저/강주헌 역', 26820)
(138, '두근두근 1학년, 우리는 널 사랑해!', '전영신 글/근홍 그림', 13050)
(139, '몬스터 캠핑장', '정주영 글/김현민 그림', 12600)
(140, '말뚝들', '김홍 저', 15120)
(141, '어린이 같은 말 다른 뜻 사전', '박세랑 글그림', 16020)
(142, '2026 위포트 공기업 NCS 통합기본서 (PSAT형+모듈형+피듈형+실전 모의고사)', '위포트 연구소 저', 24300)
(143, '기분이 태도가 되지 않게 (헬로키티 에디션)', '레몬심리 저/박영란 역', 16200)
(144, '불변의 법칙', '모건 하우절 저/이수경 역', 22500)
(145, '오래된 세계의 농담', '이다혜 저', 16200)
(146, '눈물을 마시는 새 세트', '이영도 저', 59400)
(147, '된다! 하루 만에 끝내는 제미나이 활용법', '권서림 저', 18000)
(148, '데일 카네기 긍정태도론', '데일 카네기 저/박선령 역', 15210)
(149, '명료함', '탁민 오 저', 17820)
(150, '2026 문동균 한국사 한 권으로 모든 것을 정리하는 판서노트', '문동균 편저', 15300)

In [103]:
conn = sqlite3.connect('_books.db')
cursor = conn.cursor()

# 데이터 삭제
cursor.execute('DELETE FROM books')

conn.commit()    
cursor.close()
conn.close()

In [ ]:
import pymysql

try :
    con = pymysql.connect(
        host = 'localhost', # '127.0.0.1',
        user = 'root',
        password = '1234',
        database = 'wntrade',
        charset ='utf8'
    )
    cursor = con.cursor()
    print("접속 OK")
    print("작업 후 커서 및 MySQL 서버 접속 종료하세요")


except Exception as ex :
    print("접속 실패 :", ex)
    print("MySQL 서비스가 실행 중인지 확인 요망!!!")
    

# 테이블 생성
create_query = '''  
CREATE TABLE IF NOT EXISTS books (
    ranking INTEGER PRIMARY KEY,
    title VARCHAR(255),
    author VARCHAR(100),
    price INTEGER
)
'''
cursor.execute(create_query)

# 데이터 삽입
insert_sql = "INSERT INTO books (ranking, title, author, price) VALUES (%s, %s, %s, %s)"

for index, book in bestseller_df.iterrows():
    cursor.execute(insert_sql, (index, book['title'][:255], book['author'][:100], book['price']))

con.commit()

# 데이터 조회
cursor.execute('SELECT * FROM books')
rows = cursor.fetchall()
for row in rows:
    print(row)

cursor.close()
con.close()

접속 OK
작업 후 커서 및 MySQL 서버 접속 종료하세요
나의 완벽한 장례식
진보를 위한 주식투자
박곰희 연금 부자 수업
괴테는 모든 것을 말했다
ETS 토익 정기시험 기출문제집 1000 Vol. 5 RC
ETS 토익 정기시험 기출문제집 1000 Vol. 5 LC
죽은 왕녀를 위한 파반느 (양장 특별판)
자몽살구클럽
2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상
너를 아끼며 살아라
모순
돈의 방정식
자본주의 시대에서 살아남기 위한 최소한의 경제 공부
1,000만 원으로 3년 안에 300만 원 월배당 만들기
위버멘쉬
엄마가 유령이 되었어!
안녕이라 그랬어
2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하
최소한의 삼국지
싯다르타
2026 심우철 실전 동형 모의고사 Season 2
사이토 히토리의 어떻게 살 것인가
돈의 심리학 (50만 부 기념 뉴 에디션)
더블 클릭
사카모토 데이즈 25 더블특전판
부처님 말씀대로 살아보니
캔들차트 하나로 끝내는 추세추종 투자
코스피 1만 넥스트 레벨
혼모노
해커스 토익 기출 VOCA (보카)
나의 첫 월배당 ETF
이해찬 회고록
설민석의 한국사 대모험 36
코스모스
향기로운 꽃은 늠름하게 핀다 18 더블특전판
운명을 보는 기술
교사를 지키는 단단한 학급경영
어른의 행복은 조용하다
2026 써니 행정법총론 실전동형 모의고사
2026 큰별쌤 최태성의 별별한국사 기출 500제 한국사능력검정시험 심화(1,2,3급)
주식투자 무작정 따라하기
절창 切創
아주 작은 습관의 힘 (50만 부 기념 스페셜 에디션)
2026 문동균 한국사 국가직 대비 실전 봉투 모의고사
2026 심우철 실전 동형 모의고사 Season 1
내가 돈을 벌고 있다는 착각
최소한의 한국사
내 심장을 쏴라
2026 선재국어 결승선 봉투 모의고사
2026 문동균 한국사 문단속 적중 최종병기 FINAL 모의고사
내 친구는 왜 그럴까?
급류
김재우의 기본 동사 100
다크 심리학
해커스 일본어 첫걸음 : 일본어 기초 20일 독학 완성!
SQL 자격검정 실전문제
렛뎀 이론
니체의 초월자
ETS 토익 단기공략 750+ (LC+RC)
프로젝트 헤일메리 (영화 특별판)
여덟 단어
데일 카네기 인간관계론 (50만부 돌파 초판 무삭제 완역본)
브람스를 좋아하세요...
긴긴밤
블루 아카이브 공식 4컷 청춘? 일상! 블루 아카이브 특별판
2026 문동균 한국사 D-30 문단속 모의고사
인생을 위한 최소한의 생각
오늘 밤, 세계에서 이 사랑이 사라진다 해도
이게 되네? 제미나이 완전 미친 활용법 81제
세이노의 가르침
단다단 19
우리는 언제나 다시 만나
데미안
체인소 맨 22
이기적 유전자 The Selfish Gene
2026 황철곤 행정학 실전동형 모의고사 SEASON 1
떠난 것은 돌아오지 않는다
신뢰 게임
너를 미워할 시간에 나를 사랑하기로 했다
세종의 나라 1
나쁜 일이 있어도 나쁜 날은 아니야
부의 인문학 (20만부 기념 개정증보판)
인간 실격
의사 어벤저스 25
Again! 뒤집어본 영문법
할매
원피스 ONE PIECE 113
돈의 속성 400쇄 리커버
쇼펜하우어 인생수업 (30만 부 기념 개정증보판)
소년이 온다
Go Go 카카오프렌즈 39 칠레
나는 소망한다 내게 금지된 것을
2026 심승아 Simple·Detail 소방학개론 심봉사 심승아 봉투 모의고사
ETF 투자의 모든 것
편안함의 습격
일본 광고 카피 도감
세종의 나라 2
최상위권의 생기부
어른의 품격을 채우는 100일 필사 노트
흔한남매 21
해커스 보카 Hackers Vocabulary
은애하는 도적님아 대본집 세트
해커스 일본어 첫걸음 히라가나 가타카나 쓰기노트
데일리 필로소피
쾌적한 사회의 불쾌함
2026 이유진 국어 백일기도 모의고사 [結(결) 적중]
달러 자산 1억으로 평생 월급 완성하라 (2026 투자 전략 특별판)
행복할 거야 이래도 되나 싶을 정도로
기적의 초등 신문 2026
2026 선재국어 출발선 봉투 모의고사
부모는 가장 좋은 입시 멘토다
1984
2026 유휘운 행정법총론 실전동형 모의고사
절대수익 우량주 매매법
규칙파괴자
하루 한 장 나의 어휘력을 위한 필사 노트
스킵과 로퍼 11 더블 특전판
ETS 토익기출 파트별 VOCA 보카
어른의 그릇
이방인
2026 이유진 국어 백일기도 모의고사 [承(승)_시간단축]
정답은 있다
뇌는 어떻게 나를 조종하는가
새들이 전하는 짧은 철학
2026 이유진 국어 백일기도 모의고사 [轉(전) 극한훈련]
눈과 돌멩이
어머니의 집밥을 먹을 수 있는 횟수는 328번 남았습니다
반짝반짝 1학년, 학교는 널 기다려!
손자병법
김재우의 기초 영어회화 100
메이지의 영원한 삶을 위해
존리의 부자되기 습관
해커스 토익 RC Reading(리딩) 기본서
비실비실 선생님 11
초판본 데미안
AI 시대 십 대를 위한 논어
총 균 쇠
두근두근 1학년, 우리는 널 사랑해!
몬스터 캠핑장
말뚝들
어린이 같은 말 다른 뜻 사전
2026 위포트 공기업 NCS 통합기본서 (PSAT형+모듈형+피듈형+실전 모의고사)
기분이 태도가 되지 않게 (헬로키티 에디션)
불변의 법칙
오래된 세계의 농담
눈물을 마시는 새 세트
된다! 하루 만에 끝내는 제미나이 활용법
데일 카네기 긍정태도론
명료함
2026 문동균 한국사 한 권으로 모든 것을 정리하는 판서노트
(1, '나의 완벽한 장례식', '조현선 저', 17100)
(2, '진보를 위한 주식투자', '이광수 저', 19800)
(3, '박곰희 연금 부자 수업', '박곰희 저', 18900)
(4, '괴테는 모든 것을 말했다', '스즈키 유이 저/이지수 역', 15300)
(5, 'ETS 토익 정기시험 기출문제집 1000 Vol. 5 RC', 'ETS 저', 19800)
(6, 'ETS 토익 정기시험 기출문제집 1000 Vol. 5 LC', 'ETS 저', 19800)
(7, '죽은 왕녀를 위한 파반느 (양장 특별판)', '박민규 저', 18000)
(8, '자몽살구클럽', '한로로 저', 10800)
(9, '2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 상', '최태성 저', 17100)
(10, '너를 아끼며 살아라', '나태주 저', 16650)
(11, '모순', '양귀자 저', 11700)
(12, '돈의 방정식', '모건 하우절 저/박영준 역', 25200)
(13, '자본주의 시대에서 살아남기 위한 최소한의 경제 공부', '백억남(김욱현) 저', 25200)
(14, '1,000만 원으로 3년 안에 300만 원 월배당 만들기', '인생업(임승현) 저', 20700)
(15, '위버멘쉬', '프리드리히 니체 저', 16020)
(16, '엄마가 유령이 되었어!', '노부미 글그림/이기웅 역', 10800)
(17, '안녕이라 그랬어', '김애란 저', 15120)
(18, '2026 큰별쌤 최태성의 별별한국사 한국사능력검정시험 심화(1,2,3급) 하', '최태성 저', 16650)
(19, '최소한의 삼국지', '최태성 저/이성원 감수', 17550)
(20, '싯다르타', '헤르만 헤세 저/박병덕 역', 7200)
(21, '2026 심우철 실전 동형 모의고사 Season 2', '심우철 저', 13500)
(22, '사이토 히토리의 어떻게 살 것인가', '사이토 히토리 저/황미숙 역', 11700)
(23, '돈의 심리학 (50만 부 기념 뉴 에디션)', '모건 하우절 저/이지연 역', 22320)
(24, '더블 클릭', '알간지 저', 17100)
(25, '사카모토 데이즈 25 더블특전판', '스즈키 유우토 글그림', 5850)
(26, '부처님 말씀대로 살아보니', '토니 페르난도 저/강정선 역', 17010)
(27, '캔들차트 하나로 끝내는 추세추종 투자', '성승현 저', 22500)
(28, '코스피 1만 넥스트 레벨', '박시동 저', 19800)
(29, '혼모노', '성해나 저', 16200)
(30, '해커스 토익 기출 VOCA (보카)', 'David Cho 저', 11610)
(31, '나의 첫 월배당 ETF', '김정란 저', 19800)
(32, '이해찬 회고록', '이해찬 저', 20700)
(33, '설민석의 한국사 대모험 36', '설민석, 남이담 글/정현희 그림/강석화 감수', 14400)
(34, '코스모스', '칼 에드워드 세이건 저/홍승수 역', 19800)
(35, '향기로운 꽃은 늠름하게 핀다 18 더블특전판', '미카미 사카 글그림', 5400)
(36, '운명을 보는 기술', '박성준 저', 16920)
(37, '교사를 지키는 단단한 학급경영', '이종혁 저', 16200)
(38, '어른의 행복은 조용하다', '태수 저', 16020)
(39, '2026 써니 행정법총론 실전동형 모의고사', '박준철 편저', 14400)
(40, '2026 큰별쌤 최태성의 별별한국사 기출 500제 한국사능력검정시험 심화(1,2,3급)', '최태성 저', 19800)
(41, '주식투자 무작정 따라하기', '윤재수 저', 22500)
(42, '절창 切創', '구병모 저', 16200)
(43, '아주 작은 습관의 힘 (50만 부 기념 스페셜 에디션)', '제임스 클리어 저/이한이 역', 16200)
(44, '2026 문동균 한국사 국가직 대비 실전 봉투 모의고사', '문동균 편저', 11700)
(45, '2026 심우철 실전 동형 모의고사 Season 1', '심우철 저', 13500)
(46, '내가 돈을 벌고 있다는 착각', 'commonD 저', 17820)
(47, '최소한의 한국사', '최태성 저', 16200)
(48, '내 심장을 쏴라', '정유정 저', 16200)
(49, '2026 선재국어 결승선 봉투 모의고사', '이선재 편저', 25200)
(50, '2026 문동균 한국사 문단속 적중 최종병기 FINAL 모의고사', '문동균 편저', 14400)
(51, '내 친구는 왜 그럴까?', '최현주 글/이화경 그림', 15120)
(52, '급류', '정대건 저', 12600)
(53, '김재우의 기본 동사 100', '김재우 저', 19800)
(54, '다크 심리학', '다크 사이드 프로젝트 저', 19710)
(55, '해커스 일본어 첫걸음 : 일본어 기초 20일 독학 완성!', '해커스 일본어연구소 저', 12510)
(56, 'SQL 자격검정 실전문제', '한국데이터진흥원 저', 17460)
(57, '렛뎀 이론', '멜 로빈스 저/윤효원 역', 18000)
(58, '니체의 초월자', '프리드리히 니체 저/김철 편역', 15210)
(59, 'ETS 토익 단기공략 750+ (LC+RC)', 'ETS 저', 17550)
(60, '프로젝트 헤일메리 (영화 특별판)', '앤디 위어 저/강동혁 역', 19800)
(61, '여덟 단어', '박웅현 저', 15300)
(62, '데일 카네기 인간관계론 (50만부 돌파 초판 무삭제 완역본)', '데일 카네기 저/임상훈 역', 10350)
(63, '브람스를 좋아하세요...', '프랑수아즈 사강 저/김남주 역', 9000)
(64, '긴긴밤', '루리 글그림', 11250)
(65, '블루 아카이브 공식 4컷 청춘? 일상! 블루 아카이브 특별판', '돈미니 저/블루 아카이브 원저', 47700)
(66, '2026 문동균 한국사 D-30 문단속 모의고사', '문동균 편저', 14400)
(67, '인생을 위한 최소한의 생각', '신영준, 고영성 저', 17820)
(68, '오늘 밤, 세계에서 이 사랑이 사라진다 해도', '이치조 미사키 저/권영주 역', 12600)
(69, '이게 되네? 제미나이 완전 미친 활용법 81제', '오힘찬 저', 21600)
(70, '세이노의 가르침', '세이노(SayNo) 저', 6480)
(71, '단다단 19', '타츠 유키노부 글그림', 5400)
(72, '우리는 언제나 다시 만나', '윤여림 글/안녕달 그림', 10800)
(73, '데미안', '헤르만 헤세 저/전영애 역', 7200)
(74, '체인소 맨 22', '후지모토 타츠키 글그림', 5400)
(75, '이기적 유전자 The Selfish Gene', '리처드 도킨스 저/홍영남, 이상임 역', 18000)
(76, '2026 황철곤 행정학 실전동형 모의고사 SEASON 1', '황철곤 저', 14400)
(77, '떠난 것은 돌아오지 않는다', '줄리언 반스 저/정영목 역', 16200)
(78, '신뢰 게임', '현순엽, 김진국, 박정식 저', 22000)
(79, '너를 미워할 시간에 나를 사랑하기로 했다', '윤서진 저', 16920)
(80, '세종의 나라 1', '김진명 저', 19800)
(81, '나쁜 일이 있어도 나쁜 날은 아니야', '정문정 글/피도크 그림/천근아 감수', 15120)
(82, '부의 인문학 (20만부 기념 개정증보판)', '브라운스톤(우석) 저', 15300)
(83, '인간 실격', '다자이 오사무 저', 8100)
(84, '의사 어벤저스 25', '고희정 글/조승연 그림/류정민 감수', 14220)
(85, 'Again! 뒤집어본 영문법', '오성호 저', 13410)
(86, '할매', '황석영 저', 15120)
(87, '원피스 ONE PIECE 113', '오다 에이이치로 글그림', 5850)
(88, '돈의 속성 400쇄 리커버', '김승호 저', 16020)
(89, '쇼펜하우어 인생수업 (30만 부 기념 개정증보판)', '쇼펜하우어 저 / 김지민 역', 15750)
(90, '소년이 온다', '한강 저', 13500)
(91, 'Go Go 카카오프렌즈 39 칠레', '김미영 글/김정한 그림', 15210)
(92, '나는 소망한다 내게 금지된 것을', '양귀자 저', 13500)
(93, '2026 심승아 Simple·Detail 소방학개론 심봉사 심승아 봉투 모의고사', '심승아 저', 8100)
(94, 'ETF 투자의 모든 것', '문일호 저', 18900)
(95, '편안함의 습격', '마이클 이스터 저/김원진 역', 19800)
(96, '일본 광고 카피 도감', '오하림 저', 16920)
(97, '세종의 나라 2', '김진명 저', 19800)
(98, '최상위권의 생기부', '정성민, 김혜린, 임혁기 저', 40500)
(99, '어른의 품격을 채우는 100일 필사 노트', '김종원 저', 18000)
(100, '흔한남매 21', '흔한남매 원저/백난도 글/유난희 그림/흔한컴퍼니 감수', 15120)
(101, '해커스 보카 Hackers Vocabulary', 'David Cho 저', 15210)
(102, '은애하는 도적님아 대본집 세트', '이선 저', 47700)
(103, '해커스 일본어 첫걸음 히라가나 가타카나 쓰기노트', '해커스 일본어연구소 저', 7200)
(104, '데일리 필로소피', '라이언 홀리데이, 스티븐 핸슬먼 저/장원철 역', 16200)
(105, '쾌적한 사회의 불쾌함', '구마시로 도루 저/이정미 역', 18900)
(106, '2026 이유진 국어 백일기도 모의고사 [結(결) 적중]', '이유진 편저', 30600)
(107, '달러 자산 1억으로 평생 월급 완성하라 (2026 투자 전략 특별판)', '채부심(채상욱) 저', 18900)
(108, '행복할 거야 이래도 되나 싶을 정도로', '일홍 저', 16200)
(109, '기적의 초등 신문 2026', '강버들, 민경원, 이유정, 채윤경, 임소연 글', 17820)
(110, '2026 선재국어 출발선 봉투 모의고사', '이선재 편저', 25200)
(111, '부모는 가장 좋은 입시 멘토다', '박성오 저', 16920)
(112, '1984', '조지 오웰 저/정회성 역', 9900)
(113, '2026 유휘운 행정법총론 실전동형 모의고사', '유휘운 편저', 9900)
(114, '절대수익 우량주 매매법', '성경호 저', 35100)
(115, '규칙파괴자', '데이비드 가드너 저/김태훈 역', 22500)
(116, '하루 한 장 나의 어휘력을 위한 필사 노트', '유선경 저', 21420)
(117, '스킵과 로퍼 11 더블 특전판', '타카마츠 미사키 글그림/신혜선 역', 5400)
(118, 'ETS 토익기출 파트별 VOCA 보카', 'ETS 저', 11700)
(119, '어른의 그릇', '조윤제 저', 17100)
(120, '이방인', '알베르 까뮈 저/김화영 역', 9000)
(121, '2026 이유진 국어 백일기도 모의고사 [承(승)_시간단축]', '이유진 편저', 25200)
(122, '정답은 있다', '이정효 저', 16200)
(123, '뇌는 어떻게 나를 조종하는가', '크리스 나이바우어 저/김윤종 역', 16920)
(124, '새들이 전하는 짧은 철학', '필리프 J. 뒤부아, 엘리즈 루소 저/박효은 역', 15300)
(125, '2026 이유진 국어 백일기도 모의고사 [轉(전) 극한훈련]', '이유진 편저', 25200)
(126, '눈과 돌멩이', '위수정, 김혜진, 성혜령, 이민진, 정이현 저 외 1명\r\n                                        \n정보 더 보기/감추기\n\n\n\n위수정\n김혜진\n성혜령\n', 16200)
(127, '어머니의 집밥을 먹을 수 있는 횟수는 328번 남았습니다', '우와노 소라 저/박춘상 역', 15120)
(128, '반짝반짝 1학년, 학교는 널 기다려!', '전영신 글/근홍 그림', 13050)
(129, '손자병법', '손자 저/소준섭 역', 11700)
(130, '김재우의 기초 영어회화 100', '김재우 저', 17010)
(131, '메이지의 영원한 삶을 위해', '크리스토퍼 엣지 글/민지현 역', 11700)
(132, '존리의 부자되기 습관', '존리 저', 18000)
(133, '해커스 토익 RC Reading(리딩) 기본서', 'David Cho 저', 16920)
(134, '비실비실 선생님 11', '후쿠치 카미오 글그림', 5400)
(135, '초판본 데미안', '헤르만 헤세 저/이순학 역', 1980)
(136, 'AI 시대 십 대를 위한 논어', '최태규 저', 16920)
(137, '총 균 쇠', '재레드 다이아몬드 저/강주헌 역', 26820)
(138, '두근두근 1학년, 우리는 널 사랑해!', '전영신 글/근홍 그림', 13050)
(139, '몬스터 캠핑장', '정주영 글/김현민 그림', 12600)
(140, '말뚝들', '김홍 저', 15120)
(141, '어린이 같은 말 다른 뜻 사전', '박세랑 글그림', 16020)
(142, '2026 위포트 공기업 NCS 통합기본서 (PSAT형+모듈형+피듈형+실전 모의고사)', '위포트 연구소 저', 24300)
(143, '기분이 태도가 되지 않게 (헬로키티 에디션)', '레몬심리 저/박영란 역', 16200)
(144, '불변의 법칙', '모건 하우절 저/이수경 역', 22500)
(145, '오래된 세계의 농담', '이다혜 저', 16200)
(146, '눈물을 마시는 새 세트', '이영도 저', 59400)
(147, '된다! 하루 만에 끝내는 제미나이 활용법', '권서림 저', 18000)
(148, '데일 카네기 긍정태도론', '데일 카네기 저/박선령 역', 15210)
(149, '명료함', '탁민 오 저', 17820)
(150, '2026 문동균 한국사 한 권으로 모든 것을 정리하는 판서노트', '문동균 편저', 15300)